services:
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"   # UI web
      - "1025:1025"   # SMTP

  app:
    environment:
      SMTP_HOST: mailpit
      SMTP_PORT: "1025"
      SMTP_STARTTLS: "false"
      SEED_DEMO: "true"
    depends_on:
      - mosquitto
      - mailpit
